spring:
  application:
    name: ingsis
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5439/users-db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
          audience: ${AUTH0_AUDIENCE}

okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: ${AUTH0_ISSUER_URI}
    # Replace with the API Identifier for your Auth0 API.
    audience: ${AUTH0_AUDIENCE}

server:
  port: ${API_PORT}
  address: 0.0.0.0