spring:
  application:
    name: ingsis
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: ${AUTH0_ISSUER_URI}
    # Replace with the API Identifier for your Auth0 API.
    audience: ${AUTH0_AUDIENCE}


azure:
  storage:
    account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
    account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
    blob-endpoint: ${AZURE_STORAGE_BLOB_ENDPOINT}