name: CI
on:
  push:
    branches: [ "dev","main" ]
  pull_request:
    branches: [ "dev","main" ]

jobs:
  ci:
    uses: IngsisPrintScript/workflows-and-actions/.github/workflows/ci.yml@main